### PR TITLE
Move lines up and down with multiple selections

### PR DESCRIPTION
**Pull request by abe33**
This PR continue the work you started and add the fix for the issues mentioned by @izuzak when moving lines around a soft wrapped line.

BTW I think the test on moving line down with a fold just below may be a false positive, because when testing in Atom the fold do expand, but the test contradict that. I plan to investigate that in the next days.

### CODE REVIEW

**Comment by abe33** [comment]
I forgot to mention that I had to merge back master to properly work on that. As many changes were made in-between I couldn't build Atom in the state where your branch was when I took it.

**Comment by lpommers** [comment]
@abe33 Thanks a bunch for this PR, I'll take a closer look at this tonight, but it looks great! :clap: :bow:  I'm sorry I've sort of neglected this PR for a bit, I've been busy in my personal life. I mean to get back into working on this, hopefully this week or next.

**Comment by abe33** [comment]
@lpommers No problem, I can understand. And you already did a wonderful work on that PR. I'll ping you when I think this is ready to merge, I already thought about some possible refactoring, because, as is, I'll hit some internal methods of the `DisplayBuffer` and I thought of a way to rewrite that without the if branch.

**Comment by abe33** [comment]
@lpommers It should be :ok: to merge now, the folding issue is now solved and I took the opportunity to clean up the test descriptions to make it more clear what they test.

**Pull request merged**
